### PR TITLE
Update version to 0.2.0

### PR DESCRIPTION
**Pull request by yuhattor**

### CODE REVIEW

**Comment by horihiro** [comment]
Should the `package.json` have `contributors` property?
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#people-fields-author-contributors

**Comment by yuhattor** [comment]
sure, of course
will add all the member:)

**Review by horihiro — COMMENTED** [review]
LGTM

**Review by Coerbil — COMMENTED** [review]
Live

**Pull request merged**
